include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/src/l10n/generated/**
    - lib/src/core/database/app_database.g.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    cascade_invocations: true
    close_sinks: true
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_relative_imports: true
    require_trailing_commas: true
