name: pencatatan_keuangan
description: Personal finance tracking application for recording daily transactions and generating insights.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  drift: ^2.17.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.24
  intl: ^0.20.2
  csv: ^6.0.0
  pdf: ^3.10.8
  fl_chart: ^0.68.0

# Dev tooling & code generation
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.9.0
  drift_dev: ^2.17.0
  riverpod_generator: ^2.5.1

flutter:
  uses-material-design: true
