name: project
description: >-
  Bootstrap Flutter application showcasing Material 3, Riverpod, Drift,
  modular routing, and localization scaffolding.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: 2.13.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.3
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.4
  sqlite3_flutter_libs: ^0.5.40

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.13.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
